repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.1
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/facebook/pyrefly-pre-commit
  rev: 0.44.1
  hooks:
    - id: pyrefly-check
      pass_filenames: false
      language: system
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.8.19
  hooks:
    - id: uv-export
      name: main dependencies
      args: [--no-dev, --output-file, requirements.txt]
    - id: uv-export
      name: dev dependencies
      args: [--only-group, dev, --output-file, requirements-dev.txt]
    - id: uv-lock

